git:
  depth: 1

language: cpp

compiler:
 - gcc

branches:
  only:
    - master

before_install:
 - pwd
 - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
 - echo "yes" | sudo apt-add-repository ppa:openmw/openmw
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-wave-dev libboost-system-dev libboost-filesystem-dev libboost-thread-dev
 - sudo apt-get install -qq libbullet-dev
 - sudo apt-get install -qq libopenal-dev
 - sudo apt-get install -qq libenet-dev libvorbisfile3 libogg-dev libvorbis-dev
 - sudo apt-get install -qq libogre-1.9-dev
 - sudo apt-get install -qq libmygui-dev
 - sudo apt-get install -qq libsdl2-dev

before_script:
 - mkdir build
 - cd build
 - cmake ..

script:
 - make -j2

notifications:
  irc:
    channels:
      - "chat.freenode.net#stuntrally"
    on_success: never
    on_failure: never
